### ISSUE TITLE
Setup/Configure Azure Functions

### ISSUE THREAD

**Issue by JLaveta** [ad440-cloud-project/API#4]
Create an initial API using Azure functions. 

For now, this can just be a sample API. The point of this task is to get some sort of API demo up and running and to get Azure Functions configured properly.

Eventually, we will need to have this API get a temporary SAS token from Azure Storage so files can be uploaded.

**Comment by gshields5541** [comment]
Yes, I think that’s was what I was trying to do with file-upload-service.js

Gerald

**Comment by JLaveta** [comment]
Sample API, from the basic Azure tutorial is up and running:

https://ddfnapp.azurewebsites.net/api/hello/?name=Dave

The Azure Functions resource had already been created, so reading through the tutorial and configuring a few small things only took about half an hour.

Total time: 30 minutes

**Comment by gshields5541** [comment]
Yes, I created the functions, though please check a little bit. It took me about an hour

Gerald

**Comment by gshields5541** [comment]
Are you using this tutorial ? https://docs.microsoft.com/en-us/azure/storage/blobs/storage-upload-process-images?tabs=nodejsv10

**Comment by JLaveta** [comment]
No, I am not following that tutorial, though it looks like there is some useful information in there, so thanks for sharing!

Toddy wants us to use an API to generate a SAS token in order to grant read/write access to the storage container. The tutorial you linked appears to use a different solution. I have been working on SAS token generation. Once I have that figured out, it should just be a matter of calling the API.

**Comment by JLaveta** [comment]
Closing as API has been fully created. 

Total time was 30 minutes.
